import React from 'react';
import { UserProfile } from '../components/UserProfile';
import { LoadingSpinner } from '../components/LoadingSpinner';

interface DashboardProps {
  className?: string;
}

export const Dashboard: React.FC<DashboardProps> = ({ className }) => {
  return (
    <div className={`dashboard-page ${className || ''}`}>
      <div className="page-header">
        <h1>Dashboard</h1>
        <p>Generated by Frontend Sprint Agent</p>
      </div>
      
      <div className="page-content">
        <div className="widget-grid">
          <div className="widget">
            <UserProfile />
          </div>
          
          <div className="widget">
            <h4>System Status</h4>
            <LoadingSpinner />
          </div>
          
          <div className="widget">
            <h4>Quick Actions</h4>
            <button onClick={() => window.location.reload()}>
              🔄 Refresh Data
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
